### ISSUE TITLE
Improve buildkit docs

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-buildkit#313]
This ticket is not to track progress on improving documentation, but rather simply to form a group decision on a *plan* for how to improve buildkit doc...

### The problem

Currently, buildkit doc is spread out over several partially-overlapping sources:

* [dedicated site](https://buildkit.civicrm.org/#/tutorials)
* [`README.md` file](https://github.com/civicrm/civicrm-buildkit/blob/master/README.md)
* [`/docs` directory](https://github.com/civicrm/civicrm-buildkit/tree/master/doc)
* [Dev Guide](https://docs.civicrm.org/dev/en/master/requirements/)
* [one large SE answer](https://civicrm.stackexchange.com/questions/635/how-do-i-set-up-dev-environment-with-buildkit/639#639)
* CLI help with `civibuild --help`

Further, many of these documentation sources do not make the presence of the other sources apparent to new users.

At the very least, I would like to see some consolidation and more inter-linking. But I think it's worth stepping back and thinking a little bigger. My hope is that upon closing this issue, a clear plan will exist to help consolidate and improve the buildkit documentation.

I have some ideas, which I'll share in the comments.

**Comment by seanmadsen** [comment]
## My vision for buildkit documentation:

### Improve CLI help

For now, do these steps for `civibuild` (highest priority). At some point in the future, consider doing the same for other CLI tools with sparse help (e.g. `civilint`, `cividist` etc)

1. respond to a `--help` flag (`civibuild` already does this, but some of the other commands don't)
1. separate help by command
1. make it visually cleaner
1. document all options comprehensively

Also, specifically for `civibuild`: 

1. add `civibuild types` command to list available build types

The "do-it-right" approach for civibuild, to me, seems like it would mean re-creating civibuild with Symfony so we get a full help system (as is available with `cv` for example). But that's probably too much to ask for just trying to improve docs. So instead, I propose we re-write [this help message](https://github.com/civicrm/civicrm-buildkit/blob/master/src/civibuild.app.sh#L9) to be cleaner and more comprehensive.


### Put "official docs" in the Developer Guide 

1. Decide to make a section within the Developer Guide which serves as the "official" location for buildkit docs
1. Flesh out this section with the following info
    * what buildkit does, and what comes with it
    * installing/upgrading/removing buildkit, with instructions specific 
    * basic usage, examples, and tutorials for tools that are part of buildkit and not documented elsewhere (e.g. `civibuild`, `cividist`, etc.)
1. Bring in content from other sources listed at the top of this issue
1. Be clear to readers about what this section does *not* cover, and point them to it. For example:
    * Don't cover anything about tools that ship with buildkit but are documented elsewhere (e.g. amp, civix)
    * Don't cover *commands and options* for `civibuild` and other tools which should offer this documentation natively. Okay to provide some examples here, but we want readers to understand that the full documentation for commands and their options is available via CLI help


### Remove other doc sources

1. Make buildkit.civicrm.org redirect to the official docs
*I'm very sorry to say this to whomever created this site -- it's beautiful -- but as someone trying to learn buildkit, I honestly find the site to be a disservice. I'm happy to elaborate on this point if necessary.*
1. Thin out the README file (once its content is moved to Dev Guide)
1. Remove `/doc` folder (once its content is moved to Dev Guide)
1. Provide links to relevant Dev Guide sections within popular SE questions like [this one](https://civicrm.stackexchange.com/questions/635/how-do-i-set-up-dev-environment-with-buildkit)

**Comment by seanmadsen** [comment]
Content migration underway: https://github.com/civicrm/civicrm-dev-docs/pull/189

**Comment by seanmadsen** [comment]
We've been making some progress on this grand plan, so to simplify things I'm breaking this ticket out into separate tickets now. 

Here's where we're at. 

* [x] Better `civibuild` CLI help - done in #330 and #331 
* [ ] `civibuild types` command - TODO in #334 
* [x] Migrate docs to Dev Guide - done in https://github.com/civicrm/civicrm-dev-docs/pull/189 and #332 
* [ ] - Remove buildkit site - TODO in #333
